name = "kkablemon"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3d336c843794133cbdc281e1d1d5fb540d5837bb1183b2604ceb1207ac1c82f"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
