name = "kkablemon"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c635680b585541de660e4ba5f890d1709f9a155bbd8a444f0503fbff4b0098ad"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
