name = "kkablemon"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0627873f8e309f502059c3b6cc36aa12c9eb379492227f947092f3b98dbed3a0"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
