name = "kkablemon"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b93c133f205dfda677df2dddc5d4e10319ebbdc9a566702bc7c6fedef67527dd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
