startSound = false
minMemory = 4.0
errorTitle = "Error: this modpack needs at least 4 GB RAM!"
errorDescription = "Open CurseForge settings > click on Minecraft > under Allocated Memory set 4192MB or more."
